#!/bin/sh
set -e
package_name=zram-config-biglinux
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/init-zram-swapping"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/init-zram-swapping"
;;
esac
exit 0
