#!/bin/sh
set -e
package_name=zram-config-biglinux
mkdir -p "/usr/share/dpkgdivert/zram-config-biglinux"
case "$1" in
  install)
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/zram-config-biglinux/usrbininit-zram-swapping" --rename "/usr/bin/init-zram-swapping"
    ;;
  upgrade)
if [ "$(dpkg-divert --list "/usr/bin/init-zram-swapping")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/zram-config-biglinux/usrbininit-zram-swapping" --rename "/usr/bin/init-zram-swapping"
fi
;;
esac
exit 0
